const ru = {
  "login.title": "Вход в личный кабинет",
  "login.login": "Логин",
  "login.btn": "ВОЙТИ",
  "logout.btn": "ВЫЙТИ",
  "login.showpass": "Показать",
  "login.hidepass": "Скрыть",
  "login.error.password.length": "Пароль должен быть не менее 5 символов",
  "login.error.password.required": "Пароль обязателен",
  "login.error.email.required": "Логин обязателен",
  "settings.title": "Настройки",
  "calendar.title": "Календарь",
  "mytask.title": "Мои задачи",
  "estimate.title": "Смета",
  "create.title": "Создать",
  "location.permission": "Разрешение на доступ к местоположению отклонено",
  "location.openSettings": "Открыть настройки",
  "map.search": "Поиск",
  "map.yourLocation": "Ваше местоположение",
  "language.title": "Язык",
  "pushMessage.title": "Push уведомления",
  "biometric.title": "Биометрия",
  "language.ru": "Русский",
  "language.ua": "Украинский",
  "title.off": "Выключено",
  "theme.light": "Светлая",
  "theme.dark": "Темная",
};

const ua = {
  "login.title": "Вхід в особистий кабінет",
  "login.login": "Логін",
  "login.btn": "УВІЙТИ",
  "logout.btn": "ВИЙТИ",
  "login.showpass": "Показати",
  "login.hidepass": "Сховати",
  "login.error.password.length": "Пароль повинен бути не менше 5 символів",
  "login.error.password.required": "Пароль обов'язковий",
  "login.error.email.required": "Логін обов'язковий",
  "settings.title": "Налаштування",
  "calendar.title": "Календар",
  "mytask.title": "Мої завдання",
  "estimate.title": "Кошторис",
  "create.title": "Створити",
  "location.permission": "Дозвіл на доступ до місцезнаходження відхилено",
  "location.openSettings": "Відкрити налаштування",
  "map.search": "Пошук",
  "map.yourLocation": "Ваше місцезнаходження",
  "language.title": "Мова",
  "pushMessage.title": "Push повідомлення",
  "biometric.title": "Біометрія",
  "language.ru": "Російська",
  "language.ua": "Українська",
  "title.off": "Вимкнено",
  "theme.light": "Світла",
  "theme.dark": "Темна",
};

export { ru, ua };
